### ISSUE TITLE
Using capybara to scrape

### ISSUE THREAD

**Issue by sebyx07** [YusukeIwaki/capybara-playwright-driver#46]
Hey, I get this error when I try to use it:

```ruby
Capybara.register_driver(:playwright) do |_|
  Capybara::Playwright::Driver.new(nil,browser_type: :chromium, headless: false)
end
    
session = Capybara::Session.new(:playwright)
session.visit "https://google.com"
```

trace:

```
 Failure/Error: visit 'https://google.com'

     Playwright::Error:
       Error: stack[83].file: expected string, got object
     # /home/superuser/.rvm/gems/ruby-3.0.2/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/promises.rb:1257:in `wait_until_resolved!'
     # /home/superuser/.rvm/gems/ruby-3.0.2/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/promises.rb:1471:in `value!'
     # /home/superuser/.rvm/gems/ruby-3.0.2/gems/playwright-ruby-client-1.16.0/lib/playwright/connection.rb:68:in `send_message_to_server'
     # /home/superuser/.rvm/gems/ruby-3.0.2/gems/playwright-ruby-client-1.16.0/lib/playwright/channel.rb:34:in `block in send_message_to_server_result'
     # /home/superuser/.rvm/gems/ruby-3.0.2/gems/playwright-ruby-client-1.16.0/lib/playwright/channel.rb:67:in `with_logging'
     # /home/superuser/.rvm/gems/ruby-3.0.2/gems/playwright-ruby-client-1.16.0/lib/playwright/channel.rb:33:in `send_message_to_server_result'
     # /home/superuser/.rvm/gems/ruby-3.0.2/gems/playwright-ruby-client-1.16.0/lib/playwright/channel.rb:20:in `send_message_to_server'
     # /home/superuser/.rvm/gems/ruby-3.0.2/gems/playwright-ruby-client-1.16.0/lib/playwright/channel_owners/browser_type.rb:14:in `launch'
     # /home/superuser/.rvm/gems/ruby-3.0.2/gems/playwright-ruby-client-1.16.0/lib/playwright_api/browser_type.rb:88:in `launch'
     # /home/superuser/.rvm/gems/ruby-3.0.2/gems/capybara-playwright-driver-0.1.6/lib/capybara/playwright/browser_runner.rb:72:in `playwright_browser'
     # /home/superuser/.rvm/gems/ruby-3.0.2/gems/capybara-playwright-driver-0.1.6/lib/capybara/playwright/browser_runner.rb:90:in `start'
     # /home/superuser/.rvm/gems/ruby-3.0.2/gems/capybara-playwright-driver-0.1.6/lib/capybara/playwright/driver.rb:40:in `create_playwright_browser'
     # /home/superuser/.rvm/gems/ruby-3.0.2/gems/capybara-playwright-driver-0.1.6/lib/capybara/playwright/driver.rb:27:in `playwright_browser'
     # /home/superuser/.rvm/gems/ruby-3.0.2/gems/capybara-playwright-driver-0.1.6/lib/capybara/playwright/driver.rb:20:in `browser'
     # /home/superuser/.rvm/gems/ruby-3.0.2/gems/capybara-3.36.0/lib/capybara/session.rb:278:in `visit'
```

this works fine for me

```ruby
Playwright.create(playwright_cli_executable_path: './node_modules/.bin/playwright') do |playwright|
  playwright.chromium.launch(headless: false) do |browser|
    page = browser.new_page
    page.goto('https://google.com')
  end
end
```

**Comment by sebyx07** [comment]
Update:

this code works inside `irb`
```ruby
Playwright.create(playwright_cli_executable_path: './node_modules/.bin/playwright') do |playwright|
  playwright.chromium.launch(headless: false) do |browser|
....
```
but inside `rails c` it doesn't, I get the same

`Error: stack[83].file: expected string, got object`

I also tried it in a new rails app, and there it works. maybe it conflicts with some of the existing gems

this is very strange, never happened to me

**Comment by sebyx07** [comment]
Update:

having `spring` gem causes the error

here is my temporary fix for bin/spring

```ruby
#!/usr/bin/env ruby

# This file loads Spring without using Bundler, in order to be fast.
# It gets overwritten when you run the `spring binstub` command.

unless defined?(Spring)
  require 'rubygems'
  require 'bundler'

  lockfile = Bundler::LockfileParser.new(Bundler.default_lockfile.read)
  spring = lockfile.specs.detect { |spec| spec.name == 'spring' }
  playwright = lockfile.specs.detect { |spec| spec.name == 'playwright-ruby-client' }
  return if playwright

  if spring
    Gem.use_paths Gem.dir, Bundler.bundle_path.to_s, *Gem.path
    gem 'spring', spring.version
    require 'spring/binstub'
  end
end
```

Would be cool if it can be solved with having spring enabled

**Comment by YusukeIwaki** [comment]
@sebyx07 Hi, thank you very much for your kind reporting.

This issue is caused by https://github.com/YusukeIwaki/playwright-ruby-client/pull/168
I will fix playwright-ruby-client soon. Sorry for inconvenience.

**Comment by YusukeIwaki** [comment]
@sebyx07 I fixed the problem in playwright-ruby-client. You can now use capybara-playwright-driver with Spring by updating playwright-ruby-client to 1.16.1. (Just try `bundle update playwright-ruby-client` )

I checked it works as expected with the code below:

```
Capybara.register_driver(:playwright) do |app|
  Capybara::Playwright::Driver.new(app,
    browser_type: :chromium,
    headless: false,
    playwright_cli_executable_path: './node_modules/.bin/playwright')
end
    
session = Capybara::Session.new(:playwright)
session.visit "https://google.com"
```
