### ISSUE TITLE
Error on addStackToTracingNoReply

### ISSUE THREAD

**Issue by YusukeIwaki** [YusukeIwaki/capybara-playwright-driver#68]
This driver internally receives many errors like this. (This can be observed with environment variable `DEBUG=1`)

```
SEND>{:id=>586, :guid=>"localUtils", :method=>"addStackToTracingNoReply", :params=>{:callData=>{:id=>585, :stack=>[{:file=>"/Users/yusuke-iwaki/src/github.com/YusukeIwaki/capybara-playwright-driver/spec/feature/example_spec.rb", :line=>91, :function=>"block (4 levels) in <top (required)>"}, {:file=>"/Users/yusuke-iwaki/src/github.com/YusukeIwaki/capybara-playwright-driver/lib/capybara/playwright/node.rb", :line=>22, :function=>"with_playwright_element_handle"}, {:file=>"/Users/yusuke-iwaki/src/github.com/YusukeIwaki/capybara-playwright-driver/spec/feature/example_spec.rb", :line=>91, :function=>"block (3 levels) in <top (required)>"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/capybara-3.39.2/lib/capybara/result.rb", :line=>48, :function=>"block in each"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/capybara-3.39.2/lib/capybara/result.rb", :line=>45, :function=>"loop"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/capybara-3.39.2/lib/capybara/result.rb", :line=>45, :function=>"each"}, {:file=>"/Users/yusuke-iwaki/src/github.com/YusukeIwaki/capybara-playwright-driver/spec/feature/example_spec.rb", :line=>90, :function=>"block (2 levels) in <top (required)>"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb", :line=>263, :function=>"instance_exec"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb", :line=>263, :function=>"block in run"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb", :line=>511, :function=>"block in with_around_and_singleton_context_hooks"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb", :line=>468, :function=>"block in with_around_example_hooks"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb", :line=>486, :function=>"block in run"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb", :line=>626, :function=>"block in run_around_example_hooks_for"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb", :line=>352, :function=>"call"}, {:file=>"/Users/yusuke-iwaki/src/github.com/YusukeIwaki/capybara-playwright-driver/spec/feature/example_spec.rb", :line=>8, :function=>"block (2 levels) in <top (required)>"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb", :line=>457, :function=>"instance_exec"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb", :line=>457, :function=>"instance_exec"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb", :line=>390, :function=>"execute_with"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb", :line=>628, :function=>"block (2 levels) in run_around_example_hooks_for"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb", :line=>352, :function=>"call"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb", :line=>629, :function=>"run_around_example_hooks_for"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb", :line=>486, :function=>"run"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb", :line=>468, :function=>"with_around_example_hooks"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb", :line=>511, :function=>"with_around_and_singleton_context_hooks"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb", :line=>259, :function=>"run"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb", :line=>646, :function=>"block in run_examples"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb", :line=>642, :function=>"map"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb", :line=>642, :function=>"run_examples"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb", :line=>607, :function=>"run"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb", :line=>121, :function=>"block (3 levels) in run_specs"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb", :line=>121, :function=>"map"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb", :line=>121, :function=>"block (2 levels) in run_specs"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/configuration.rb", :line=>2068, :function=>"with_suite_hooks"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb", :line=>116, :function=>"block in run_specs"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/reporter.rb", :line=>74, :function=>"report"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb", :line=>115, :function=>"run_specs"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb", :line=>89, :function=>"run"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb", :line=>71, :function=>"run"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb", :line=>45, :function=>"invoke"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/exe/rspec", :line=>4, :function=>"<top (required)>"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/bin/rspec", :line=>25, :function=>"load"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/bin/rspec", :line=>25, :function=>"<top (required)>"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/cli/exec.rb", :line=>58, :function=>"load"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/cli/exec.rb", :line=>58, :function=>"kernel_load"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/cli/exec.rb", :line=>23, :function=>"run"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/cli.rb", :line=>483, :function=>"exec"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor/command.rb", :line=>27, :function=>"run"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor/invocation.rb", :line=>127, :function=>"invoke_command"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor.rb", :line=>392, :function=>"dispatch"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/cli.rb", :line=>31, :function=>"dispatch"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor/base.rb", :line=>485, :function=>"start"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/cli.rb", :line=>25, :function=>"start"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/exe/bundle", :line=>48, :function=>"block in <top (required)>"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/friendly_errors.rb", :line=>103, :function=>"with_friendly_errors"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/exe/bundle", :line=>36, :function=>"<top (required)>"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/bin/bundle", :line=>25, :function=>"load"}, {:file=>"/Users/yusuke-iwaki/.rbenv/versions/3.1.3/bin/bundle", :line=>25, :function=>"<main>"}]}}}
RECV>{"id"=>586, "error"=>{"error"=>{"message"=>"callData.stack[0].column: expected number, got undefined", "stack"=>"Error: callData.stack[0].column: expected number, got undefined\n    at tNumber (/Users/yusuke-iwaki/src/github.com/YusukeIwaki/capybara-playwright-driver/node_modules/playwright-core/lib/protocol/validatorPrimitives.js:47:9)\n    at /Users/yusuke-iwaki/src/github.com/YusukeIwaki/capybara-playwright-driver/node_modules/playwright-core/lib/protocol/validatorPrimitives.js:108:21\n    at /Users/yusuke-iwaki/src/github.com/YusukeIwaki/capybara-playwright-driver/node_modules/playwright-core/lib/protocol/validato...", "name"=>"Error"}}}
```

**Comment by YusukeIwaki** [comment]
This is an issue of playwright-ruby-client.
