### ISSUE TITLE
wait_for_load_state(state: "networkidle")でPlaywright::Transport::AlreadyDisconnectedErrorが起きる

### ISSUE THREAD

**Issue by kiyo-e** [YusukeIwaki/capybara-playwright-driver#72]
`wait_for_load_state(state: 'networkidle')` のあと、sleepでdefault_max_wait_time以上の時間を待つと、下記エラーが出てテストに失敗します。

```
/Users/hoge/Desktop/playwright-test/node_modules/playwright-core/lib/server/dispatchers/dispatcher.js:344
            originalMetadata.endTime = (0, _utils.monotonicTime)();
                                     ^

TypeError: Cannot set properties of undefined (setting 'endTime')
    at DispatcherConnection.dispatch (/Users/hoge/Desktop/playwright-test/node_modules/playwright-core/lib/server/dispatchers/dispatcher.js:344:38)
    at transport.onmessage (/Users/hoge/Desktop/playwright-test/node_modules/playwright-core/lib/cli/driver.js:52:57)
    at Immediate.<anonymous> (/Users/hoge/Desktop/playwright-test/node_modules/playwright-core/lib/protocol/transport.js:77:34)
    at process.processImmediate (node:internal/timers:478:21)

Node.js v20.11.0
```

再現コードは以下です。
```
require 'rails_helper'

RSpec.describe "Users", type: :system do
  before do
    driven_by(:playwright)
  end

  it "creates a User" do
    visit new_user_path
    Capybara.current_session.driver.with_playwright_page do |page|
      page.wait_for_load_state(state: 'networkidle')
      sleep 30
      expect(page).to have_content("User was successfully created.")
    end
  end
end
```

フルバージョンのコードはこちらにあります。
https://github.com/kiyo-e/playwright-test

**Comment by YusukeIwaki** [comment]
capybara-playwright-driverが依存しているplaywright-ruby-client 1.40以降で問題が発生するようになってしまったようです。

https://github.com/YusukeIwaki/playwright-ruby-client/pull/275/files#diff-adce952276e8519a3452551163960780acb107f414cff525ab3514f2ef080309
WaitHelperでwaitForEventInfo before/after の機能を使うようになった（公式のライブラリでは1.9からすでにこの形になっていたのをplaywright-ruby-clientでは1.40でこの形になった）影響と考えられます。

**Comment by YusukeIwaki** [comment]
```
END>{:id=>8, :guid=>"page@567e169a77d6eaf0d0be9eeded340906", :method=>"waitForEventInfo", :params=>{:info=>{:waitId=>"bdfd45393bf9a277d3558ad9f0d59e6f", :phase=>"after"}}}
RECV>{"id"=>7}
RECV>{"id"=>8}
SEND>{:id=>9, :guid=>"page@567e169a77d6eaf0d0be9eeded340906", :method=>"waitForEventInfo", :params=>{:info=>{:waitId=>"bdfd45393bf9a277d3558ad9f0d59e6f", :phase=>"after", :error=>#<Playwright::TimeoutError: Timeout 1000ms exceeded.
=========================== logs ===========================
"networkidle" event fired
============================================================>}}}
/Users/yusuke-iwaki/Downloads/playwright-1.42.0-mac/package/lib/server/dispatchers/dispatcher.js:344
            originalMetadata.endTime = (0, _utils.monotonicTime)();
                                     ^
```

playwright-ruby-clientの不具合で、waitForEventInfoが2度通知されていることが問題のようでした。

**Comment by YusukeIwaki** [comment]
ref: https://github.com/YusukeIwaki/playwright-ruby-client/issues/285

**Comment by kiyo-e** [comment]
ご対応ありがとうございました、助かりました！
